#!/usr/bin/env bash
# tools/release/prepare-release.sh — rewrite Package.swift for an SPM-consumer release.
#
# AUDIT §7 — Package.swift in this repo is a *dev-mode* manifest that points at a
# locally-vendored BareKit.xcframework so the monorepo `swift build` works. SPM
# consumers using `.package(url: "...", from: "0.1.0")` cannot resolve that path
# in their checkout, so for a real release we need a manifest that uses
# `binaryTarget(url:, checksum:)` pointing at the GitHub Release artifacts.
#
# This script downloads the artifacts for a given tag (must already have been
# uploaded by release.yml), computes their SHA-256 checksums, and rewrites
# Package.swift in place to use URL-based binary targets.
#
# Usage:
#   tools/release/prepare-release.sh v0.1.0
#
# Pre-conditions:
#   - The tag `v0.1.0` exists on GitHub.
#   - `release.yml` has uploaded the xcframework zips to that tag's release.
#   - `gh` CLI is authenticated against the repo.
#
# Post-conditions:
#   - Package.swift is rewritten with URL+checksum binaryTargets.
#   - The dev-mode manifest is preserved as Package.swift.dev for monorepo work.
#   - A summary of computed checksums is printed.
#
# After running this script the maintainer should:
#   1. Inspect the rewritten Package.swift.
#   2. Commit it: `git commit -am "release: pin v0.1.0 binary targets"`.
#   3. Move the tag to the new commit: `git tag -fa v0.1.0 -m "v0.1.0"` then
#      `git push origin v0.1.0 --force-with-lease`.
#   4. SPM consumers using `from: "0.1.0"` now resolve a URL-based manifest.

set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
    echo "usage: $0 <version>   (e.g. v0.1.0)" >&2
    exit 2
fi

REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"
cd "$REPO_ROOT"

REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner)"
RELEASE_TAG="$VERSION"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "[prepare-release] repo=$REPO  tag=$RELEASE_TAG  workdir=$WORKDIR"

# 1. Fetch the artifact list from the release.
mapfile -t ARTIFACTS < <(gh release view "$RELEASE_TAG" --repo "$REPO" --json assets -q '.assets[].name' | grep '\.xcframework\.zip$')
if [ "${#ARTIFACTS[@]}" -eq 0 ]; then
    echo "[prepare-release] error: no .xcframework.zip artifacts found at release $RELEASE_TAG" >&2
    exit 3
fi
echo "[prepare-release] found ${#ARTIFACTS[@]} xcframework artifacts at release"

# 2. Download each + compute SHA-256.
declare -a TARGETS
declare -A CHECKSUMS
for asset in "${ARTIFACTS[@]}"; do
    name="${asset%.xcframework.zip}"
    echo "[prepare-release]   downloading $asset..."
    gh release download "$RELEASE_TAG" --repo "$REPO" --pattern "$asset" --dir "$WORKDIR"
    sha=$(shasum -a 256 "$WORKDIR/$asset" | awk '{print $1}')
    CHECKSUMS["$name"]="$sha"
    TARGETS+=("$name")
    echo "[prepare-release]   $name -> $sha"
done

# 3. Back up the dev-mode manifest so monorepo dev keeps working.
cp Package.swift Package.swift.dev

# 4. Emit the URL-based manifest.
URL_BASE="https://github.com/$REPO/releases/download/$RELEASE_TAG"
{
    cat <<EOF
// swift-tools-version:5.10
// QVAC Swift Client — SPM-consumer manifest (release ${RELEASE_TAG}).
//
// Generated by tools/release/prepare-release.sh — do not edit by hand. The dev-mode
// manifest that uses local vendored paths is preserved as Package.swift.dev.

import PackageDescription

let package = Package(
    name: "QVACClient",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
    ],
    products: [
        .library(name: "QVACClient", targets: ["QVACClient"]),
    ],
    targets: [
EOF
    for name in "${TARGETS[@]}"; do
        cat <<EOF
        .binaryTarget(
            name: "${name}",
            url: "${URL_BASE}/${name}.xcframework.zip",
            checksum: "${CHECKSUMS[$name]}"
        ),
EOF
    done
    cat <<'EOF'
        .target(
            name: "QVACClient",
            dependencies: [
                .target(name: "BareKit", condition: .when(platforms: [.iOS])),
            ],
            path: "Sources/QVACClient",
            resources: [
                .copy("Resources/worker.mobile.bundle.js"),
            ]
        ),
        .testTarget(
            name: "QVACClientUnitTests",
            dependencies: ["QVACClient"],
            path: "Tests/QVACClientUnitTests",
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "QVACClientIntegrationTests",
            dependencies: ["QVACClient"],
            path: "Tests/QVACClientIntegrationTests"
        ),
    ]
)
EOF
} > Package.swift

echo
echo "[prepare-release] ✅ Package.swift rewritten. Summary:"
echo "[prepare-release]    URL base: $URL_BASE"
echo "[prepare-release]    Binary targets: ${#TARGETS[@]}"
echo
echo "[prepare-release] Next steps:"
echo "  1. Review:        diff Package.swift.dev Package.swift"
echo "  2. Sanity check:  swift package describe"
echo "  3. Commit:        git add Package.swift Package.swift.dev && \\"
echo "                    git commit -m 'release: pin ${RELEASE_TAG} binary targets'"
echo "  4. Move the tag:  git tag -fa ${RELEASE_TAG} -m '${RELEASE_TAG}'"
echo "  5. Push:          git push origin main && git push origin ${RELEASE_TAG} --force-with-lease"
