// QVACGeneratedRoundTripTests.generated.swift
//
// AUTO-GENERATED from the exact @qvac/sdk@0.17.0 contract/schema.json
// gitHead: e8b440665a053a9efe852f04c3601da44f0d55d8
// Exercises every concrete initializer plus both strict discriminated unions.
// DO NOT EDIT BY HAND.

import XCTest
@testable import QVACClient

final class QVACGeneratedRoundTripTests: XCTestCase {
    private func assertRoundTrip<T: Codable & Equatable>(
        _ value: T,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let encoded = try JSONEncoder.qvac.encode(value)
        let decoded = try JSONDecoder().decode(T.self, from: encoded)
        XCTAssertEqual(decoded, value, file: file, line: line)
    }

    func test_all_39_request_leaves_construct_encode_and_decode() throws {
        let value0 = AudioGenStreamRequest(caption: "fixture", modelId: "fixture", bpm: 1, duration: 1.25, keyscale: "fixture", lyrics: "fixture", requestId: "fixture", seed: 1, timesignature: "fixture", vocalLanguage: "fixture")
        try assertRoundTrip(value0)
        try assertRoundTrip(QVACRequest.audioGenStream(value0))
        let value1 = BatchCompletionStreamRequest(modelId: "fixture", prompts: [], captureThinking: true, emitRawDeltas: true, requestId: "fixture", stream: true, toolDialect: "fixture")
        try assertRoundTrip(value1)
        try assertRoundTrip(QVACRequest.batchCompletionStream(value1))
        let value2 = BciTranscribeRequest(modelId: "fixture", neuralData: .string("fixture"), metadata: true, requestId: "fixture")
        try assertRoundTrip(value2)
        try assertRoundTrip(QVACRequest.bciTranscribe(value2))
        let value3 = BciTranscribeStreamRequest(modelId: "fixture", metadata: true, requestId: "fixture", streamOpts: .string("fixture"))
        try assertRoundTrip(value3)
        try assertRoundTrip(QVACRequest.bciTranscribeStream(value3))
        let value4 = CancelRequest(operation: "fixture", clearCache: true, kind: "fixture", modelId: "fixture", requestId: "fixture")
        try assertRoundTrip(value4)
        try assertRoundTrip(QVACRequest.cancel(value4))
        let value5 = ClassifyRequest(image: "fixture", modelId: "fixture", channels: 1.25, height: 1, topK: 1, width: 1)
        try assertRoundTrip(value5)
        try assertRoundTrip(QVACRequest.classify(value5))
        let value6 = CompletionOrchestrateRequest(history: [], modelId: "fixture", stream: true, captureThinking: true, emitRawDeltas: true, generationParams: .string("fixture"), kvCache: .string("fixture"), maxToolTurns: 1, requestId: "fixture", responseFormat: .string("fixture"), toolDialect: "fixture", tools: [])
        try assertRoundTrip(value6)
        try assertRoundTrip(QVACRequest.completionOrchestrate(value6))
        let value7 = CompletionStreamRequest(history: [], modelId: "fixture", stream: true, captureThinking: true, emitRawDeltas: true, generationParams: .string("fixture"), kvCache: .string("fixture"), requestId: "fixture", responseFormat: .string("fixture"), toolDialect: "fixture", tools: [])
        try assertRoundTrip(value7)
        try assertRoundTrip(QVACRequest.completionStream(value7))
        let value8 = DeleteCacheRequest(all: true, kvCacheKey: "fixture", modelId: "fixture")
        try assertRoundTrip(value8)
        try assertRoundTrip(QVACRequest.deleteCache(value8))
        let value9 = DiffusionStreamRequest(modelId: "fixture", prompt: "fixture", autoResizeRefImage: true, batchCount: 1, cachePreset: "fixture", cfgScale: 1.25, guidance: 1.25, height: 1, imgCfgScale: 1.25, increaseRefIndex: true, initImage: "fixture", initImages: [], lora: "fixture", negativePrompt: "fixture", samplingMethod: "fixture", scheduler: "fixture", seed: 1, steps: 1, strength: 1.25, upscale: .string("fixture"), vaeTiling: true, width: 1)
        try assertRoundTrip(value9)
        try assertRoundTrip(QVACRequest.diffusionStream(value9))
        let value10 = DownloadAssetRequest(assetSrc: "fixture", requestId: "fixture", seed: true, withProgress: true)
        try assertRoundTrip(value10)
        try assertRoundTrip(QVACRequest.downloadAsset(value10))
        let value11 = EmbedRequest(modelId: "fixture", text: .string("fixture"), requestId: "fixture")
        try assertRoundTrip(value11)
        try assertRoundTrip(QVACRequest.embed(value11))
        let value12 = FinetuneRequest(modelId: "fixture", operation: "fixture", options: .string("fixture"), requestId: "fixture", withProgress: true)
        try assertRoundTrip(value12)
        try assertRoundTrip(QVACRequest.finetune(value12))
        let value13 = GetLoadedModelInfoRequest(modelId: "fixture")
        try assertRoundTrip(value13)
        try assertRoundTrip(QVACRequest.getLoadedModelInfo(value13))
        let value14 = GetModelInfoRequest(name: "fixture")
        try assertRoundTrip(value14)
        try assertRoundTrip(QVACRequest.getModelInfo(value14))
        let value15 = GetSystemResourcesRequest(sample: true)
        try assertRoundTrip(value15)
        try assertRoundTrip(QVACRequest.getSystemResources(value15))
        let value16 = HeartbeatRequest(delegate: .string("fixture"))
        try assertRoundTrip(value16)
        try assertRoundTrip(QVACRequest.heartbeat(value16))
        let value17 = LoadModelRequest(modelType: "fixture", delegate: .string("fixture"), modelConfig: .string("fixture"), modelId: "fixture", modelName: "fixture", modelSrc: "fixture", requestId: "fixture", seed: true, withProgress: true)
        try assertRoundTrip(value17)
        try assertRoundTrip(QVACRequest.loadModel(value17))
        let value18 = LoggingStreamRequest(id: "fixture")
        try assertRoundTrip(value18)
        try assertRoundTrip(QVACRequest.loggingStream(value18))
        let value19 = ModelRegistryGetModelRequest(registryPath: "fixture", registrySource: "fixture")
        try assertRoundTrip(value19)
        try assertRoundTrip(QVACRequest.modelRegistryGetModel(value19))
        let value20 = ModelRegistryListRequest()
        try assertRoundTrip(value20)
        try assertRoundTrip(QVACRequest.modelRegistryList(value20))
        let value21 = ModelRegistrySearchRequest(addon: "fixture", engine: "fixture", filter: "fixture", quantization: "fixture")
        try assertRoundTrip(value21)
        try assertRoundTrip(QVACRequest.modelRegistrySearch(value21))
        let value22 = OcrStreamRequest(image: .string("fixture"), modelId: "fixture", options: .string("fixture"))
        try assertRoundTrip(value22)
        try assertRoundTrip(QVACRequest.ocrStream(value22))
        let value23 = PluginInvokeRequest(handler: "fixture", modelId: "fixture", params: .string("fixture"))
        try assertRoundTrip(value23)
        try assertRoundTrip(QVACRequest.pluginInvoke(value23))
        let value24 = PluginInvokeStreamRequest(handler: "fixture", modelId: "fixture", params: .string("fixture"))
        try assertRoundTrip(value24)
        try assertRoundTrip(QVACRequest.pluginInvokeStream(value24))
        let value25 = ProvideRequest(firewall: .string("fixture"))
        try assertRoundTrip(value25)
        try assertRoundTrip(QVACRequest.provide(value25))
        let value26 = RagRequest(operation: "fixture", chunk: true, chunkOpts: .string("fixture"), deleteOnClose: true, documents: [], ids: [], modelId: "fixture", n: 1.25, progressInterval: 1.25, query: "fixture", requestId: "fixture", topK: 1.25, withProgress: true, workspace: "fixture")
        try assertRoundTrip(value26)
        try assertRoundTrip(QVACRequest.rag(value26))
        let value27 = ResumeRequest()
        try assertRoundTrip(value27)
        try assertRoundTrip(QVACRequest.resume(value27))
        let value28 = StateRequest()
        try assertRoundTrip(value28)
        try assertRoundTrip(QVACRequest.state(value28))
        let value29 = StopProvideRequest()
        try assertRoundTrip(value29)
        try assertRoundTrip(QVACRequest.stopProvide(value29))
        let value30 = SuspendRequest()
        try assertRoundTrip(value30)
        try assertRoundTrip(QVACRequest.suspend(value30))
        let value31 = TextToSpeechRequest(modelId: "fixture", text: "fixture", description: "fixture", emotion: "fixture", expressivity: "fixture", inputType: "fixture", noise: "fixture", pace: "fixture", pitch: "fixture", quality: "fixture", reverb: "fixture", sentenceStream: true, sentenceStreamLocale: "fixture", sentenceStreamMaxChunkScalars: 1.25, stream: true, voice: "fixture", voiceDescription: "fixture")
        try assertRoundTrip(value31)
        try assertRoundTrip(QVACRequest.textToSpeech(value31))
        let value32 = TextToSpeechStreamRequest(modelId: "fixture", accumulateSentences: true, description: "fixture", emotion: "fixture", expressivity: "fixture", flushAfterMs: 1.25, inputType: "fixture", maxBufferScalars: 1.25, noise: "fixture", pace: "fixture", pitch: "fixture", quality: "fixture", reverb: "fixture", sentenceDelimiterPreset: "fixture", voice: "fixture", voiceDescription: "fixture")
        try assertRoundTrip(value32)
        try assertRoundTrip(QVACRequest.textToSpeechStream(value32))
        let value33 = TranscribeRequest(audioChunk: .string("fixture"), modelId: "fixture", metadata: true, prompt: "fixture", requestId: "fixture")
        try assertRoundTrip(value33)
        try assertRoundTrip(QVACRequest.transcribe(value33))
        let value34 = TranscribeStreamRequest(modelId: "fixture", emitVadEvents: true, endOfTurnSilenceMs: 1, metadata: true, parakeetStreamingConfig: .string("fixture"), prompt: "fixture", requestId: "fixture", vadRunIntervalMs: 1)
        try assertRoundTrip(value34)
        try assertRoundTrip(QVACRequest.transcribeStream(value34))
        let value35 = TranslateRequest(modelId: "fixture", modelType: "fixture", stream: true, text: .one("fixture"), context: "fixture", from: "fixture", requestId: "fixture", to: "fixture")
        try assertRoundTrip(value35)
        try assertRoundTrip(QVACRequest.translate(value35))
        let value36 = UnloadModelRequest(modelId: "fixture", clearStorage: true)
        try assertRoundTrip(value36)
        try assertRoundTrip(QVACRequest.unloadModel(value36))
        let value37 = UpscaleStreamRequest(image: "fixture", modelId: "fixture", repeats: 1)
        try assertRoundTrip(value37)
        try assertRoundTrip(QVACRequest.upscaleStream(value37))
        let value38 = VideoStreamRequest(mode: "fixture", modelId: "fixture", prompt: "fixture", cacheMode: "fixture", cachePreset: "fixture", cacheThreshold: 1.25, cfgScale: 1.25, controlFrames: [], flowShift: 1.25, fps: 1.25, height: 1, highNoiseCfgScale: 1.25, highNoiseFlowShift: 1.25, highNoiseSampler: "fixture", highNoiseScheduler: "fixture", highNoiseSteps: 1, initImage: "fixture", moeBoundary: 1.25, negativePrompt: "fixture", requestId: "fixture", samplingMethod: "fixture", scheduler: "fixture", seed: 1, steps: 1, strength: 1.25, temporalTiling: true, vaceStrength: 1.25, vaeTileOverlap: 1.25, vaeTileSize: .string("fixture"), vaeTiling: true, videoFrames: 1, width: 1)
        try assertRoundTrip(value38)
        try assertRoundTrip(QVACRequest.videoStream(value38))
    }

    func test_all_43_response_leaves_construct_encode_and_decode() throws {
        let value0 = AudioGenStreamResponse(done: true, bitsPerSample: 1, channels: 1, data: "fixture", progress: .string("fixture"), sampleRate: 1, stats: .string("fixture"), stopReason: "fixture")
        try assertRoundTrip(value0)
        try assertRoundTrip(QVACResponse.audioGenStream(value0))
        let value1 = BatchCompletionStreamResponse(events: [], done: true, ids: [], stats: .string("fixture"))
        try assertRoundTrip(value1)
        try assertRoundTrip(QVACResponse.batchCompletionStream(value1))
        let value2 = BciTranscribeResponse(done: true, error: "fixture", segment: .string("fixture"), stats: .string("fixture"), text: "fixture")
        try assertRoundTrip(value2)
        try assertRoundTrip(QVACResponse.bciTranscribe(value2))
        let value3 = BciTranscribeStreamResponse(done: true, error: "fixture", segment: .string("fixture"), stats: .string("fixture"), text: "fixture")
        try assertRoundTrip(value3)
        try assertRoundTrip(QVACResponse.bciTranscribeStream(value3))
        let value4 = CancelResponse(success: true, cancelled: 1, error: "fixture")
        try assertRoundTrip(value4)
        try assertRoundTrip(QVACResponse.cancel(value4))
        let value5 = ClassifyResponse(results: [], done: true)
        try assertRoundTrip(value5)
        try assertRoundTrip(QVACResponse.classify(value5))
        let value6 = CompletionOrchestrateResponse(done: true, events: [], stopReason: "fixture", toolCallback: .string("fixture"), turn: 1)
        try assertRoundTrip(value6)
        try assertRoundTrip(QVACResponse.completionOrchestrate(value6))
        let value7 = CompletionStreamResponse(events: [], done: true)
        try assertRoundTrip(value7)
        try assertRoundTrip(QVACResponse.completionStream(value7))
        let value8 = DeleteCacheResponse(success: true, error: "fixture")
        try assertRoundTrip(value8)
        try assertRoundTrip(QVACResponse.deleteCache(value8))
        let value9 = DiffusionStreamResponse(data: "fixture", done: true, elapsedMs: 1.25, outputIndex: 1.25, stats: .string("fixture"), step: 1.25, totalSteps: 1.25)
        try assertRoundTrip(value9)
        try assertRoundTrip(QVACResponse.diffusionStream(value9))
        let value10 = DownloadAssetResponse(success: true, assetId: "fixture", error: "fixture")
        try assertRoundTrip(value10)
        try assertRoundTrip(QVACResponse.downloadAsset(value10))
        let value11 = EmbedResponse(embedding: .string("fixture"), success: true, error: "fixture", stats: .string("fixture"))
        try assertRoundTrip(value11)
        try assertRoundTrip(QVACResponse.embed(value11))
        let value12 = ErrorResponse(message: "fixture", cause: .string("fixture"), code: 1.25, name: "fixture", stack: "fixture", timestamp: "fixture", typedFields: [:])
        try assertRoundTrip(value12)
        try assertRoundTrip(QVACResponse.error(value12))
        let value13 = FinetuneResponse(status: "fixture", stats: .string("fixture"))
        try assertRoundTrip(value13)
        try assertRoundTrip(QVACResponse.finetune(value13))
        let value14 = FinetuneProgressResponse(accuracy: .string("fixture"), accuracyUncertainty: .string("fixture"), currentBatch: 1, currentEpoch: 1, elapsedMs: 1.25, etaMs: 1.25, globalSteps: 1, isTrain: true, loss: .string("fixture"), lossUncertainty: .string("fixture"), modelId: "fixture", totalBatches: 1)
        try assertRoundTrip(value14)
        try assertRoundTrip(QVACResponse.finetuneProgress(value14))
        let value15 = GetLoadedModelInfoResponse(info: .string("fixture"))
        try assertRoundTrip(value15)
        try assertRoundTrip(QVACResponse.getLoadedModelInfo(value15))
        let value16 = GetModelInfoResponse(modelInfo: .string("fixture"))
        try assertRoundTrip(value16)
        try assertRoundTrip(QVACResponse.getModelInfo(value16))
        let value17 = GetSystemResourcesResponse(capabilities: .string("fixture"), sample: .string("fixture"))
        try assertRoundTrip(value17)
        try assertRoundTrip(QVACResponse.getSystemResources(value17))
        let value18 = HeartbeatResponse(number: 1.25)
        try assertRoundTrip(value18)
        try assertRoundTrip(QVACResponse.heartbeat(value18))
        let value19 = LoadModelResponse(success: true, error: "fixture", modelId: "fixture")
        try assertRoundTrip(value19)
        try assertRoundTrip(QVACResponse.loadModel(value19))
        let value20 = LoggingStreamResponse(id: "fixture", level: "fixture", message: "fixture", namespace: "fixture", timestamp: 1.25)
        try assertRoundTrip(value20)
        try assertRoundTrip(QVACResponse.loggingStream(value20))
        let value21 = ModelProgressResponse(downloadKey: "fixture", downloaded: 1.25, percentage: 1.25, total: 1.25, fileSetInfo: .string("fixture"), shardInfo: .string("fixture"))
        try assertRoundTrip(value21)
        try assertRoundTrip(QVACResponse.modelProgress(value21))
        let value22 = ModelRegistryGetModelResponse(success: true, error: "fixture", model: .string("fixture"))
        try assertRoundTrip(value22)
        try assertRoundTrip(QVACResponse.modelRegistryGetModel(value22))
        let value23 = ModelRegistryListResponse(success: true, error: "fixture", models: [])
        try assertRoundTrip(value23)
        try assertRoundTrip(QVACResponse.modelRegistryList(value23))
        let value24 = ModelRegistrySearchResponse(success: true, error: "fixture", models: [])
        try assertRoundTrip(value24)
        try assertRoundTrip(QVACResponse.modelRegistrySearch(value24))
        let value25 = OcrStreamResponse(blocks: [], done: true, error: "fixture", stats: .string("fixture"))
        try assertRoundTrip(value25)
        try assertRoundTrip(QVACResponse.ocrStream(value25))
        let value26 = PluginInvokeResponse(result: .string("fixture"))
        try assertRoundTrip(value26)
        try assertRoundTrip(QVACResponse.pluginInvoke(value26))
        let value27 = PluginInvokeStreamResponse(result: .string("fixture"), done: true)
        try assertRoundTrip(value27)
        try assertRoundTrip(QVACResponse.pluginInvokeStream(value27))
        let value28 = ProvideResponse(success: true, error: "fixture", publicKey: "fixture")
        try assertRoundTrip(value28)
        try assertRoundTrip(QVACResponse.provide(value28))
        let value29 = RagResponse(operation: "fixture", success: true, chunks: [], droppedIndices: [], error: "fixture", processed: [], result: .string("fixture"), results: [], workspaces: [])
        try assertRoundTrip(value29)
        try assertRoundTrip(QVACResponse.rag(value29))
        let value30 = RagProgressResponse(current: 1.25, operation: "fixture", stage: "fixture", timestamp: 1.25, total: 1.25, workspace: "fixture")
        try assertRoundTrip(value30)
        try assertRoundTrip(QVACResponse.ragProgress(value30))
        let value31 = ResumeResponse()
        try assertRoundTrip(value31)
        try assertRoundTrip(QVACResponse.resume(value31))
        let value32 = StateResponse(state: "fixture")
        try assertRoundTrip(value32)
        try assertRoundTrip(QVACResponse.state(value32))
        let value33 = StopProvideResponse(success: true, error: "fixture")
        try assertRoundTrip(value33)
        try assertRoundTrip(QVACResponse.stopProvide(value33))
        let value34 = SuspendResponse()
        try assertRoundTrip(value34)
        try assertRoundTrip(QVACResponse.suspend(value34))
        let value35 = TextToSpeechResponse(buffer: [], done: true, chunkIndex: 1, sentenceChunk: "fixture", stats: .string("fixture"))
        try assertRoundTrip(value35)
        try assertRoundTrip(QVACResponse.textToSpeech(value35))
        let value36 = TextToSpeechStreamResponse(buffer: [], done: true, chunkIndex: 1, sentenceChunk: "fixture", stats: .string("fixture"))
        try assertRoundTrip(value36)
        try assertRoundTrip(QVACResponse.textToSpeechStream(value36))
        let value37 = TranscribeResponse(done: true, endOfTurn: .string("fixture"), error: "fixture", segment: .string("fixture"), stats: .string("fixture"), text: "fixture", vad: .string("fixture"))
        try assertRoundTrip(value37)
        try assertRoundTrip(QVACResponse.transcribe(value37))
        let value38 = TranscribeStreamResponse(done: true, endOfTurn: .string("fixture"), error: "fixture", segment: .string("fixture"), stats: .string("fixture"), text: "fixture", vad: .string("fixture"))
        try assertRoundTrip(value38)
        try assertRoundTrip(QVACResponse.transcribeStream(value38))
        let value39 = TranslateResponse(token: "fixture", done: true, error: "fixture", stats: .string("fixture"))
        try assertRoundTrip(value39)
        try assertRoundTrip(QVACResponse.translate(value39))
        let value40 = UnloadModelResponse(success: true, error: "fixture", hasActiveModels: true, hasActiveProviders: true)
        try assertRoundTrip(value40)
        try assertRoundTrip(QVACResponse.unloadModel(value40))
        let value41 = UpscaleStreamResponse(data: "fixture", done: true, outputIndex: 1.25, stats: .string("fixture"))
        try assertRoundTrip(value41)
        try assertRoundTrip(QVACResponse.upscaleStream(value41))
        let value42 = VideoStreamResponse(data: "fixture", done: true, elapsedMs: 1.25, outputIndex: 1.25, stats: .string("fixture"), step: 1.25, totalSteps: 1.25)
        try assertRoundTrip(value42)
        try assertRoundTrip(QVACResponse.videoStream(value42))
    }

    func test_one_or_many_wire_union_round_trips_scalar_and_array() throws {
        let scalar: QVACOneOrMany<String> = .one("fixture")
        let batch: QVACOneOrMany<String> = .many(["first", "second"])
        try assertRoundTrip(scalar)
        try assertRoundTrip(batch)
    }

}
